In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [4]:
x = np.zeros((3,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
import pandas as pd

df = pd.DataFrame({"col1": [1, 2, 3, 4, 5, 6], "col2": [6, 5, 4, 3, 2, 1]}, index=[1, 1, 1, 2, 2, 2])
s1 = pd.Series([1, 2, 3], index=[2, 2, 2])
s2 = pd.Series([4, 5, 6], index=[1, 1, 1])

# Use concat to combine s1 and s2 and map them to df using the index
df['output'] = pd.concat([s1, s2]).sort_index()

print(df)


   col1  col2  output
1     1     6       4
1     2     5       5
1     3     4       6
2     4     3       1
2     5     2       2
2     6     1       3


In [5]:
x = np.ones((2,5))
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [6]:
arr = np.arange(9+1)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
arr = np.random.randint(9,size=(3,3))
print(arr)

[[1 0 6]
 [2 0 3]
 [6 2 4]]


In [8]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr1 = arr.reshape(2,4)
print(arr1)

[[1 2 3 4]
 [5 6 7 8]]


In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr.mean())

5.0


In [10]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1*arr2)
print(np.multiply(arr1,arr2))

[ 4 10 18]
[ 4 10 18]


In [11]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(np.dot(arr1,arr2))

32


In [12]:
arr = np.array([10, 20, 30, 40, 50])
print(np.std(arr))

14.142135623730951


In [13]:
arr = np.random.randint(0,100,10)
print(arr)

[69 70 90 28  6 30 45 73 35 54]


In [14]:
arr = [1, 2, 3, 4, 5]
rt = np.array(arr)
print(rt)
print(rt[2])

[1 2 3 4 5]
3


In [15]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
add = np.add(arr1,arr2)
print(add)

[5 7 9]


In [16]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
mul = np.dot(arr1,arr2)
print(mul)

32


In [17]:
arr = [1,2,3,4,5,8]
arr1 = np.array(arr)
print(arr1.reshape(2,3))

[[1 2 3]
 [4 5 8]]


In [18]:
arr = [1,2,3,4,5,6]
print(np.mean(arr))

3.5


In [19]:
arr = [1,2,3,4,5,6]
print(np.std(arr))

1.707825127659933


In [20]:
arr = [1,2,3,4,5,6]
print(np.median(arr))

3.5


In [21]:
arr = [1,2,3,4,5,6]
print(np.var(arr))

2.9166666666666665


In [22]:
arr = [1,2,3,4,5,6]
print(np.max(arr))

6


In [23]:
arr = [1,2,3,4,5,6]
print(np.min(arr))

1


In [10]:
arr = [1,2,3,4,5,6]
print(np.any(arr))

False


In [11]:
arr = [1,2,3,4,5,6]
print(np.all(arr))

True


In [26]:
arr = [1,2,3,4,5,6]
a = np.array(arr)
b = np.where(a == 6)
b

(array([5], dtype=int64),)

In [27]:
a=np.arange(12)  
b=np.where(a==6)  
b  

(array([6], dtype=int64),)

In [28]:
arr = [0,0,0,1,2,3,4,5,6]
a = np.count_nonzero(arr)
a

6

In [37]:
arr1 = [[1,7,8],[0,1,2]]
arr2 = [[3,4,5],[7,8,9]]
awe = np.array(arr1)
ass = np.array(arr2)
a = np.vstack((awe,ass))
a

array([[1, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [7, 8, 9]])

In [12]:
arr = np.arange(20)
a = np.unique(arr) 
a

array([1, 2, 3])

In [42]:
arr = np.arange(6)
a = arr.reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [43]:
arr = np.arange(12)
a = np.flip(arr)
a

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [44]:
arr = np.arange(12)
a = np.sort(arr)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [46]:
arr = np.arange(12)
a = -np.sort(-arr)
a

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [48]:
arr = np.arange(12)
a = np.where(arr == 6,1,arr)
a

array([ 0,  1,  2,  3,  4,  5,  1,  7,  8,  9, 10, 11])

In [50]:
arr = np.arange(12)
a = np.where(arr == 6)
a

(array([6], dtype=int64),)

In [14]:
arr = -np.arange(12)
a = np.absolute(arr)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [53]:
arr = np.arange(12)
a = np.sqrt(arr)
a

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479])

In [55]:
arr = np.arange(12)
a = np.log10(arr)
a

C:\Users\vivek\AppData\Local\Temp\ipykernel_732\3399768107.py:2: RuntimeWarning: divide by zero encountered in log10
  a = np.log10(arr)


array([      -inf, 0.        , 0.30103   , 0.47712125, 0.60205999,
       0.69897   , 0.77815125, 0.84509804, 0.90308999, 0.95424251,
       1.        , 1.04139269])

In [56]:
arr = np.arange(12)
a = np.exp(arr)
a

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04])

In [58]:
arr = np.arange(12)
a = np.sin(arr)
a

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021])

In [59]:
arr = np.arange(12)
a = np.cos(arr)
a

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153,  0.0044257 ])

In [61]:
arr = np.arange(12)
a = np.tan(arr)
a

array([ 0.00000000e+00,  1.55740772e+00, -2.18503986e+00, -1.42546543e-01,
        1.15782128e+00, -3.38051501e+00, -2.91006191e-01,  8.71447983e-01,
       -6.79971146e+00, -4.52315659e-01,  6.48360827e-01, -2.25950846e+02])

In [62]:
arr = np.array([0.5,14.5,4.9])
a = np.floor(arr)
a

array([ 0., 14.,  4.])

In [66]:
arr1 = np.array([0.5,14.5,4.9])
arr2 = np.array([0.5,2.5,4.9])
a = np.mod(arr1,arr2)
a

array([0., 2., 0.])

In [69]:
arr = np.arange(12)
a = np.power(arr,2)
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121],
      dtype=int32)

In [70]:
arr = np.arange(12)
a = np.sum(arr)
a

66

In [74]:
arr = np.arange(1,12)
a = np.prod(arr)
a

39916800

In [75]:
arr = np.arange(12)
a = np.cumsum(arr)
a

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66], dtype=int32)

In [81]:
arr = np.arange(1,12)
a = np.cumprod(arr)
a

array([       1,        2,        6,       24,      120,      720,
           5040,    40320,   362880,  3628800, 39916800], dtype=int32)

In [86]:
arr = np.arange(12)
arr[5] = 8
a = np.diff(arr)
a

array([ 1,  1,  1,  1,  4, -2,  1,  1,  1,  1,  1])

In [90]:
arr1 = np.random.randint(1,100,30)
arr2 = np.random.randint(1,100,30)
a = np.maximum(arr1,arr2)
print(arr1)
print(arr2)
a

[ 3 89 80 52 49 22 33 16  8 94 59 95 70 75 44 89 37 16 72 64 79 13  3 22
 93 92 47 95 29  6]
[77 64  3 20 59 60 47 69 53 95 67 88 59 17 37 92 84 23 73 44 99 59 19 51
 81 13 76 24 12 38]


array([77, 89, 80, 52, 59, 60, 47, 69, 53, 95, 67, 95, 70, 75, 44, 92, 84,
       23, 73, 64, 99, 59, 19, 51, 93, 92, 76, 95, 29, 38])

In [91]:
arr1 = np.random.randint(1,100,30)
arr2 = np.random.randint(1,100,30)
print(arr1)
print(arr2)
a = np.minimum(arr1,arr2)
a

[58 93 98 45 87  5 11 59 52  7 70 89 23 18 73 65 29 35 87 99 57 15 14 74
 15  4 14 37  6 68]
[52 51 94 54 81 93 81  7 26 86 32  3 38 32  5 26 34 52 52 61 45 29  3 43
 70 21 86 30 12 51]


array([52, 51, 94, 45, 81,  5, 11,  7, 26,  7, 32,  3, 23, 18,  5, 26, 29,
       35, 52, 61, 45, 15,  3, 43, 15,  4, 14, 30,  6, 51])

In [95]:
arr1 = np.random.randint(1,100,30)
arr2 = np.random.randint(1,100,30)
print(arr1)
print(arr2)
a = np.intersect1d(arr1,arr2)
a

[57 72 96 17 13 59 11 20 46 19 96  5 87 83  6 77 35 33 89 57 35 83  5 63
 54 72 97 54 13 15]
[39 64 88 45 10 69 62 16 43 59 65 67 80 30 87 29 44 29 48 85 75 37  7 40
 54 11 93 83 43 49]


array([11, 54, 59, 83, 87])

In [101]:
arr1 = np.random.randint(1,100,5)
arr2 = np.random.randint(1,100,5)
print(arr1)
print(arr2)
a = np.setdiff1d(arr1,arr2)
a

[46 49 17 49 69]
[17 54 91 45 91]


array([46, 49, 69])

In [102]:
arr1 = np.random.randint(1,100,5)
arr2 = np.random.randint(1,100,5)
print(arr1)
print(arr2)
a = np.corrcoef(arr1,arr2)
a

[46 42 39 92 23]
[21 17 55  1 14]


array([[ 1.        , -0.47427474],
       [-0.47427474,  1.        ]])

In [110]:
a = np.random.rand(5,5)
a

array([[0.31174132, 0.16370697, 0.78821289, 0.3857389 , 0.60982989],
       [0.41316507, 0.16155134, 0.97829335, 0.79275828, 0.70055759],
       [0.48004143, 0.50416288, 0.96691719, 0.35177197, 0.04626211],
       [0.24212032, 0.88193631, 0.42290196, 0.28877663, 0.49655254],
       [0.91053296, 0.32565685, 0.28268302, 0.75747803, 0.30160329]])

In [119]:
arr = np.arange(12)
np.random.shuffle(arr)
arr

array([ 2,  6,  7,  8,  4,  0,  9,  1, 11, 10,  5,  3])